#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_fogg_peers="0.0.1"
  jq -n --arg fogg_peers "$ver_fogg_peers" '{fogg_peers: $fogg_peers}'
}

version "$@"
