#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_fogg_peering_connection="0.0.1"
  jq -n --arg fogg_peering_connection "$ver_fogg_peering_connection" '{fogg_peering_connection: $fogg_peering_connection}'
}

version "$@"
